src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

use Vich\UploaderBundle\Mapping\Annotation as Vich;
/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable()
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="fileName")
     */
    private $imageFile;
    

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     *
     * @Assert\Range(
     *      min = 10,
     *      max = 400,
     *      minMessage = "La valeur de la surface doit etre superieur ou égal à {{ limit }}m2",
     *      maxMessage = "La valeur de la surface doit etre inferieur ou égal à {{ limit }}m2"
     * )
     */

    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     *
     * @Assert\Regex("/^[0-9]{5}$/")
     *
     * @ORM\Column(type="string", length=255)
     *
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;


    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fileName;



    public function __construct()
    {
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug():string
    {
      return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0,'', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }


    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Property
     * @throws \Exception
     */
    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile){
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    public function setFileName(?string $fileName): self
    {
        $this->fileName = $fileName;

        return $this;
    }


}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use function Sodium\add;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('imageFile', FileType::class,
                [
                    'required'=>false
                ])
            ->add('heat', ChoiceType::class,
                array(
                    'choices' => $this->getChoices()))
            ->add('options', EntityType::class,
            array(
                'required'=> false,
                'class'=> Option::class,
                'choice_label' =>'name',
                'multiple' => true))
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
        $choices = Property::HEAT;
        $output = array();
        foreach ($choices as $k => $v) {
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */
    private $repository;

    /**
     * @var ObjectManager
     */
    private $em;

    public function __construct(PropertyRepository $repository, ObjectManager $em)
    {
        $this->repository = $repository;
        $this->em  = $em;
    }

    /**
     * @Route("/property", name="property.index")
     * @param PaginatorInterface $pagination
     * @param Request $request
     * @return Response
     */
    public function index(PaginatorInterface $pagination, Request $request)
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);
        $properties = $pagination->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1),
            12
        );
        return $this->render('property/index.html.twig', [
            'current_menu'    => 'properties',
            'properties'      => $properties,
            'form'            => $form->createView()
        ]);
    }

    /**
     * @Route("/property/{slug}-{id}", name="property.show", requirements={"slug":"[a-z0-9\-]*"})
     * @param Property $property
     * @param string $slug
     * @return Response
     */
    public function show(Property $property, string $slug): Response
    {
        if ($property->getSlug() !== $slug){
            return $this->redirectToRoute(
                'property.show', [
                    'id' => $property->getId(),
                    'slug' => $property->getSlug()
                ],
                301
            );
        }
        return $this->render('property/show.html.twig', [
            'property'      => $property,
            'current_menu'  => 'properties'
        ]);
    }
}

templates/property/_property.html.twig
<div class="row ">
    {% for property in properties %}
        <div class="col-4">
            {% if property.filename %}
                <img class="card-img-top" src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb')}}" alt="{{ property.title }}" />
            {% else %}
                <img class="card-img-top" src="{{ '/images/properties/empty.jpg' | imagine_filter('thumb')}}" alt="{{ property.title }}" />
            {% endif%}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{{ path('property.show',{id : property.id, slug : property.slug}) }}">{{ property.title }}</a>
                    </h5>
                    <p class="card-text">{{ property.surface }} m2 {{ property.city }} ({{ property.postalCode }})</p>
                    <p class="text-primary">{{ property.formattedPrice }} FCFA</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Toute nos biens' %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">
                    {{ form_row(form.minSurface) }}
                </div>
                <div class="col">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col">
                    {{ form_row(form.options) }}
                </div>
                <div class="col form-group">
                    <button class="btn btn-primary">Rechercher</button>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
    <div class="container mt-4">
        <h3>Toute nos biens</h3>
        {{ include ('property/_property.html.twig') }}
        <div class="pagination">
            {{ knp_pagination_render(properties) }}
        </div>
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title  %}

{% block body %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-8">
            {% if property.filename %}
                <img class="card-img-top" src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium')}}" alt="{{ property.title }}" />
            {% else %}
                <img class="card-img-top" src="{{ '/images/properties/empty.jpg' | imagine_filter('medium')}}" alt="{{ property.title }}" />
            {% endif%}
        </div>
        <div class="col-md-4">
            <h1>{{ property.title }}</h1>
            <h2>{{ property.rooms }} pièces - {{ property.surface }} m2</h2>
            <div class="text-primary" style="font-size: 2rem; font-weight: bold;"> {{ property.formattedPrice }} FCFA</div>
            <a href="#" class="btn btn-primary">Contacter l'agence</a>
        </div>
    </div>
    <p>
        {{ property.description | nl2br }}
    </p>

    <div class="row">
        <div class="col-md-8">
            <h2>Caracteristique</h2>
            <table class="table table-striped">
                <tr>
                    <td>Surface habitable</td>
                    <td>{{ property.surface }} m2</td>
                </tr>
                <tr>
                    <td>Pièces</td>
                    <td>{{ property.rooms }}</td>
                </tr>

                <tr>
                    <td>Chambres</td>
                    <td>{{ property.bedrooms }}</td>
                </tr>
                <tr>
                    <td>Etages</td>
                    <td>{{ property.floor }}</td>
                </tr>
                <tr>
                    <td>Chauffage</td>
                    <td>{{ property.heatType }}</td>
                </tr>
            </table>
        </div>
        <div class="col-md-4">
            <h2>Specificite</h2>
            <ul class="list-group">
                {% for option in property.options %}
                    <li class="list-group-item">
                        {{ option.name }}
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}